export { default as Header } from './Header/Header'
export { default as NavBar } from './NavBar/NavBar'
export { default as Socials } from './Socials/Socials'
export { default as Footer } from './Footer/Footer'
export { default as Logo } from './Logo/Logo'
export { default as Descriptions } from './Descriptions/Descriptions'
export { default as Products } from './Products/Products'
