export { default as BannerImg } from './SDbanner.png'
export { default as LogoImg } from './sdlogo.png'
export { default as CocImg } from './coc.png'
export { default as ImmatImg } from './immatriculation.png'
export { default as CTImg } from './controletechnique.png'
export { default as ContactIcon } from './icons/contact.svg'
